
DO 
$$
DECLARE
VAL INT := 50;

BEGIN
IF VAL >=1 AND VAL<=10 THEN
RAISE NOTICE 'YOUR VALUE IS % AND IS IN RANGE B/w 1 TO 10', VAL;

ELSEIF VAL>=10 AND VAL<=20 THEN
RAISE NOTICE 'YOUR VALUE IS % AND IS IN RANGE B/w 10 TO 20' ,VAL;

ELSEIF VAL>=20 AND VAL<=30 THEN
RAISE NOTICE 'YOUR VALUE IS % AND IS IN RANGE B/w 20 TO 30' ,VAL;

ELSE
RAISE NOTICE 'YOUR VALUE IS % AND IS GREATER THAN 30', VAL;
END IF;
END;

$$


